"""init frontend rbg tables

Revision ID: 9dd4f798e528
Revises: 
Create Date: 2025-09-02 07:25:25.716987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd4f798e528'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frontend_rbg_task_submit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userName', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('taskID', sa.String(length=100), nullable=False, comment='任务ID'),
    sa.Column('taskType', sa.String(length=50), nullable=False, comment='任务类型'),
    sa.Column('data', sa.Text(), nullable=True, comment='任务附加数据'),
    sa.Column('dateTime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taskID')
    )
    op.create_index(op.f('ix_frontend_rbg_task_submit_id'), 'frontend_rbg_task_submit', ['id'], unique=False)
    op.create_index(op.f('ix_frontend_rbg_task_submit_userName'), 'frontend_rbg_task_submit', ['userName'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('task_listener',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taskID', sa.String(length=100), nullable=False, comment='任务ID'),
    sa.Column('taskStatus', sa.String(length=50), nullable=False, comment='任务状态'),
    sa.Column('taskResult', sa.Text(), nullable=True, comment='任务结果'),
    sa.ForeignKeyConstraint(['taskID'], ['frontend_rbg_task_submit.taskID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taskID')
    )
    op.create_index(op.f('ix_task_listener_id'), 'task_listener', ['id'], unique=False)
    op.create_index(op.f('ix_task_listener_taskStatus'), 'task_listener', ['taskStatus'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('upload_type', sa.String(length=20), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_clips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clip_file_name', sa.String(length=100), nullable=False),
    sa.Column('clip_file_path', sa.String(length=255), nullable=False),
    sa.Column('clip_file_url', sa.String(length=255), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_clips')
    op.drop_table('videos')
    op.drop_index(op.f('ix_task_listener_taskStatus'), table_name='task_listener')
    op.drop_index(op.f('ix_task_listener_id'), table_name='task_listener')
    op.drop_table('task_listener')
    op.drop_table('users')
    op.drop_index(op.f('ix_frontend_rbg_task_submit_userName'), table_name='frontend_rbg_task_submit')
    op.drop_index(op.f('ix_frontend_rbg_task_submit_id'), table_name='frontend_rbg_task_submit')
    op.drop_table('frontend_rbg_task_submit')
    # ### end Alembic commands ###
